//
//  GameConstants.swift
//  DotIOGame
//
//  Created by Ryan Anderson on 7/22/16.
//  Copyright © 2016 Ryan Anderson. All rights reserved.
//

import Foundation
import SpriteKit
import Darwin

let pi = CGFloat(M_PI)

class C {
    // Not all game constants are here. Yet. My goal is for all of them to be here
    // Functions do count as constants.
    static let energyTransferPercent: CGFloat = 0.85 //energy transfer percent is the grow amount that is kept when energy changes state (e.g. creature ->X% mine ->X% orbs)
    static let creaturesToAreaRatio: CGFloat = 0.0000011
    static let orbsToAreaRatio: CGFloat = 0.00002
    
    //static let camera_scaleMinimum: CGFloat = 2.5
    static let maxPlayerRadiusToScreenWidthRatio: CGFloat = 0.11285
    static let minPlayerRadiusToScreenWidthRatio: CGFloat = 0.06692
    static let warningSign_minScale: CGFloat = 0.5, warningSign_maxScale: CGFloat = 3
    
    static let orbBeacon_minimumValueRequirement: CGFloat = 20000
    
    static let creature_hitMinePercentMassReduction: CGFloat = 0.5,
        creature_minimumRadiusToApplyMineSizeReductionInsteadOfInstantDeath: CGFloat = 80,
        creature_speedDebuffTime: CGFloat = 1.5,
        creature_maxAngleChangePerSecond: CGFloat = 270,
        creature_minePropulsionSpeedActiveTime: CGFloat = 0.25,
        creature_mineCooldownTime: CGFloat = 4.5,
        creature_minRadius: CGFloat = 50,
        creature_maxRadius: CGFloat = 350,
        creature_orbSpawnUponDeathRadiusMultiplier: CGFloat = 1.7,
    creature_deathFadeOutDuration: NSTimeInterval = 0.25
    static let percentLargerRadiusACreatureMustBeToEngulfAnother: CGFloat = 1.11
    
    static func creature_passiveScoreIncreasePerSecond(givenRadius r: CGFloat) -> CGFloat {
        return pow(2, r / 110) / 1.5
    }
    
    static func creature_passiveSizeLossPerSecond(givenRadius r: CGFloat) -> CGFloat {
        //return CGFloat( 1.25 * pow(2, (r-30)/100) - 1 )
        return r / 200
    }
    
    static func creature_normalSpeed(givenRadius r: CGFloat) -> CGFloat {
        //return 60 * pow(1/2, (r - 50) / 100) + 60
        return -r/6 + 160
    }
    
    static let alertPlayerAboutLargerCreaturesInRange: CGFloat = 800
    
    static let orb_growAmounts: [GameScene.OrbType: CGFloat] = [
        .Small : 154,
        .Rich : 1500,
        .Glorious: 707
    ]
    static let orb_minRadii: [GameScene.OrbType: CGFloat] = [
        .Small: 7,
        .Rich: 22,
        .Glorious: 15
    ]
    static let orb_maxRadii: [GameScene.OrbType: CGFloat] = [
        .Small: 9,
        .Rich: 26,
        .Glorious: 20
    ]
    static let orb_pointValues: [GameScene.OrbType: Int] = [
        .Small: 1,
        .Rich: 5,
        .Glorious: 5
    ]
    static let orb_artificialLifespan: CGFloat = 20 // The reason I have this constant is because if there is a big pile of orbs somewhere that's not being touched by the player or thte ai, it shouldn't clog up the cpu. This applies for the single player version at least.
    static let orb_fadeOutForXSeconds: CGFloat = 5
    static let mine_sizeExaggeration: CGFloat = 1.3 // Makes mines look bigger, but with the same hitbox.
    
    static let randomPlayerNames = [
        "Dont eat me",
        "Dont eat me!!1",
        "Frosty",
        "Names",
        "rage quit",
        "I should be doing homework",
        "Team, guys",
        "Dude... same",
        "Patrick Star",
        "I don't like you",
        "I WORK for MY fun!",
        "Scrublord",
        "DaliLabs",
        "CaliLabs",
        "Cat",
        "MLG QuickScoper",
        "Mtn Dew",
        "Doritos",
        "BLEEEEEEHHHH",
        "Aadkngjknas",
        "0_0",
        "0______0",
        "xx_Illuminati_xx",
        "Doge",
        "I WILL EAT U",
        "Bleeeh",
        "hmmmmmm",
        "AEGWRH",
        "SPAM",
        "HUUUUUUUGH",
        "Hugh Mungus",
        "Hughh Mungus",
        "get away from me",
        "this game sucks",
        "agar.io clone!? D:",
        "Are you feeling it now mr crabs?",
        "Mr. Creeper",
        "Mr. Crabs",
        "Hmmmmmmmm",
        "Bob",
        "Casey",
        "Inky",
        "Blinky",
        "Clyde",
        "", "", "", "", "", "", "", "",
        "FeelTheBern2016",
        "XXx_Fabi0_xXX",
        "Team?",
        "Level 200 pro",
        "Say hi to Youtube!",
        "Pro team",
        "Foo", "Bar",
        "asdfghj",
        "qwerty",
        "Trump2016",
        "XXX_SLaYeR_XxX", "bob", "hmmm",
        "123", "xoxo360", "Bill Nye",
        "4Science", "A", "B", "C", "abcdefg",
        "hijklmnopqrstuv", "wxyz", "get n0sc0p3d",
        "Janny", "Jerry", "Kirk", "Dali-Labs", "Dali_Labs",
        "dalilabs", "daliLabs", "DaliLabs", "CAli Labs", "Krusty Krab",
        "Krusty Krab Pizza", "hello, world!", "Hello, world", "Rey wenderleich",
        "Pewdie Pie", "Garbanzo da fish", "Brisk Armadillo", "Edeskem", "hissing_snacks",
        "Italia", "USA", "Canada", "Mexico", "Netherlands", "Japan",
        "France", "China", "Russia", "Vlad the terrible",
        "Ammameder",
        "Aphanlaw",
        "BelieveSteve",
        "Biconsin",
        "BitFamousSteen",
        "Boscodi",
        "Buryland",
        "Castech",
        "DariScan",
        "DeanChilled",
        "Dunckla",
        "Expertelby",
        "Fairmark",
        "Freechoint",
        "Frettels",
        "Gossipessa",
        "GotNeo",
        "GoWisdom",
        "Grinderithi",
        "IffyHunterAsh",
        "Inconit",
        "Jibeator",
        "Kreerica",
        "LeakOmaha",
        "Lingony",
        "Mentight",
        "Netcowlet",
        "Punkerante",
        "Qualxon",
        "Reernore",
        "Agediali",
        "Banklemo",
        "Chergeto",
        "Chilogyre",
        "Craeguity",
        "Decksherox",
        "Devonen",
        "Dowleca",
        "Ehowerdi",
        "EliteDavAni",
        "Exorspec",
        "FamousFireInside",
        "Fitolane",
        "Fixeriteson",
        "Grassency",
        "Iliseid",
        "Infoutte",
        "Inloverlan",
        "Lukerydgua",
        "Masciler",
        "Matifyre",
        "Medingey",
        "Notesotingk",
        "Opticaram",
        "Parleyen",
        "Plentyrdov",
        "PongBlog",
        "Proterr",
        "Prudysaid",
        "Readertics",
        "Agilext",
        "Anceanst",
        "Antiteque",
        "Born2texans",
        "BroadcastSlim",
        "Comfynianab",
        "Cytaterbam",
        "Darkerextw",
        "Deskiedawt",
        "DigyTracker",
        "Emogerim",
        "Exintech",
        "Fatuire",
        "Forbascati",
        "GriffonFluent",
        "Guitarister",
        "Headlinera",
        "IncaSpark",
        "Islandason",
        "IteLao",
        "Knotritert",
        "Lontuser",
        "Lyfetsonis",
        "Madderhout",
        "Metronger",
        "Millity",
        "Pluserav",
        "Redintly",
        "Simonines",
        "Sizzlinse",
        "Acilleen",
        "Angopoly",
        "Animechia",
        "Banditebay",
        "Bersetho",
        "Bigotektr",
        "Bloomangeye",
        "Branthem",
        "CampyFirstLuda",
        "Carderdi",
        "Cinco2cuteLead",
        "Contnutic",
        "Dailiespa",
        "Dexlogam",
        "DubyaChronicle",
        "EyeSparkGlitz",
        "Fantastic",
        "Frediatify",
        "Garfirsed",
        "Goethann",
        "Invitype",
        "KidFarVirtuoso",
        "Naldchbu",
        "Phobichare",
        "Populardeco",
        "Presunico",
        "ProdigyFlames",
        "Rottnet",
        "Serialep",
        "Skierress",
        "Amtscomni",
        "Angelsojet",
        "Aprinext",
        "Bierseade",
        "Borapago",
        "BugsMister",
        "ChilledBrilliant",
        "ChromeSpoon",
        "CottonVirtuoso",
        "Datacomm",
        "Eronyxin",
        "Fideause",
        "FixRazu",
        "Inetuman",
        "Insiderpres",
        "Kathiche",
        "Kazakupti",
        "Midnightec",
        "Moonautool",
        "Musiceman",
        "Noticeabet",
        "NycBlink4me",
        "Opinish",
        "Peachamanir",
        "Poshytear",
        "Pressenda",
        "Qualsoni",
        "Raetsimal",
        "Raseguet",
        "Resortage",
        "Derpawance",
        "DerpDertrum",
        "Derphara",
        "Derpield",
        "Derpring",
        "DertrumDerp",
        "Gladbeta",
        "GladBig",
        "Gladeshe",
        "Gladidev",
        "GladKrool",
        "Gladvant",
        "GuppyHappy",
        "HappyDerp",
        "Happyfone",
        "HappyGippy",
        "Happygm",
        "HappyMunde",
        "Happyod",
        "HappyTinsPleased",
        "Pleased",
        "Pleaseder",
        "Pleasedge",
        "PleasedGlad",
        "Pleasedia",
        "PleasedSportsThrilled",
        "Pleasedus",
        "SaladGlad",
        "SantaPleased",
        "Thrilled",
        "CakeAkeake",
        "CakeCake",
        "CakePies",
        "Cakersna",
        "CakeUptake",
        "Cakeypac",
        "CartGodly",
        "Godlycite",
        "Godlyvils",
        "GorgeousPieCake",
        "PieCake",
        "PieGlossyGodly",
        "PieJeans",
        "PiemanPies",
        "Pienderpl",
        "PieRadio",
        "Piercomet",
        "Piersland",
        "PiesChosenTart",
        "PiesPieTrite",
        "PiesRiderPie",
        "Piessect",
        "PiesStylishCrossed",
        "Piessyst",
        "PiesTart",
        "PieTart",
        "PieTartGodly",
        "Pietrusbl",
        "RozCakeMind",
        "TarpanTart",
        "AppdApps",
        "ApposerApps",
        "AppsApplier",
        "AppsGeneral",
        "Appsieur",
        "Appsking",
        "AppsMake",
        "AppsSmarterFried",
        "DalasiDaliLabs",
        "DaliLabs",
        "DaliLabsDalasi",
        "DaliLabsen",
        "DaliLabsha",
        "DaliLabskt",
        "DaltonDaliLabs",
        "MakeApps",
        "Makeares",
        "Makeckle",
        "MakeDaliLabs",
        "Makeepla",
        "MakeInsider",
        "Makenbel",
        "MakePrimeWe",
        "MakerMake",
        "Makermat",
        "Makersdore",
        "MakeStrake",
        "MakeWe",
        "WeApps",
        "WeBright",
        "Avocado",
        "Avocadoan",
        "AvocadoAvocado",
        "AvocadoCucumber",
        "AvocadoSkate",
        "BobberCucumber",
        "Calicont",
        "CaliHorray",
        "CaliIfall",
        "Calinkda",
        "Calinkve",
        "Calisman",
        "Calismar",
        "CaliTomato",
        "Cucumber",
        "CucumberBibber",
        "CucumberTubber",
        "DotMango",
        "EmberCucumber",
        "FadoAvocado",
        "JibberCucumber",
        "MangoCucumber",
        "Mangoer",
        "Mangoiden",
        "Mangoldon",
        "MangoMantrap",
        "Mangood",
        "Mangoream",
        "Mangosics",
        "Mangovnet",
        "CalcesCali",
        "CaliberCali",
        "CaliCalory",
        "CaliCalves",
        "Caliersu",
        "Calierud",
        "Califtch",
        "Calinews",
        "Calingerus",
        "Calinker",
        "CaliSupreme",
        "CaliXbox",
        "CalvesCali",
        "KeepupSquid",
        "KuroCali",
        "QuoteSquidDoom",
        "RodeoCali",
        "ShatSquid",
        "SquealSquid",
        "Squidayca",
        "Squidea",
        "SquidEasyBeat",
        "Squidee",
        "Squideo",
        "Squider",
        "Squidge",
        "Squidgelm",
        "Squidgeni",
        "Squidgesi",
        "SquidIss",
        "CakeCeticHissing",
        "CakeCrake",
        "Cakehing",
        "CakeLiberty",
        "Cakelleraz",
        "Cakenden",
        "Cakernse",
        "Cakeryonyx",
        "CakeSnacks",
        "CakeSplake",
        "Caketboy",
        "Caketfor",
        "CakeTinker",
        "Caketspo",
        "Hissing",
        "HissingCake",
        "HissingGodzilla",
        "Hissingho",
        "Hissingor",
        "HissingSnacks",
        "IanCake",
        "KiwiHissing",
        "LibelLiberty",
        "Liberty",
        "LibertyAsp",
        "LibertyHissing",
        "LibertyLibel",
        "Libertymi",
        "Libertype",
        "MessageSnacks",
        "Annametragi",
        "ArsenalDj",
        "BlondeHip",
        "BoostElement",
        "Boyhousol",
        "Centelatc",
        "Chicketon",
        "Chicleso",
        "ChromeKidSmooth",
        "Citharm",
        "Commosi",
        "Coolaboomt",
        "Coralfast",
        "Corebuca",
        "Czarlitimb",
        "Dfindblem",
        "Eutelleer",
        "Evangeris",
        "Glacesterma",
        "GoldSupreme",
        "Hyposel",
        "Intindre",
        "JournalPeach",
        "Kavendiar",
        "Kevingu",
        "Keyspre",
        "Magazineou",
        "Namakered",
        "PersonalGenius",
        "PlentyLetter",
        "Analegre",
        "Anhealti",
        "Announcerer",
        "Beckertr",
        "Billiecess",
        "Bracernerso",
        "CertIntcat",
        "Clareco",
        "ClassyJideGinger",
        "Cutientum",
        "Daniolant",
        "Emmetrace",
        "Flashypher",
        "Gambitekni",
        "Goldnevela",
        "Greaticen",
        "Guipuzzle",
        "Headfouter",
        "Hemslow",
        "JidePassion",
        "KiddoLittle",
        "KitUpper",
        "KryptoInterior",
        "Kuronismeg",
        "Lashopro",
        "Medisman",
        "MegsXmc",
        "Monolin",
        "MountainThebest",
        "Musclar",
        "Ainesswo",
        "Anarcuser",
        "Avantelar",
        "Bowiecelo",
        "Calypoite",
        "Cutientiaso",
        "DemonRodeo",
        "Dollexprow",
        "Feistympri",
        "Greency",
        "Hofferry",
        "HotCriticMercy",
        "Imprill",
        "Intrine",
        "Kelsydive",
        "Lyfeldflag",
        "Markette",
        "MercyThedevil",
        "Mxenlisk",
        "NeilCharms",
        "Newsenotoc",
        "Nothinginet",
        "Novaswire",
        "Payeech",
        "Phentium",
        "Purcomax",
        "Remelete",
        "Reportsma",
        "Scoptigo",
        "Shangme",
        "Abouthbro",
        "Arshipha",
        "Avagosi",
        "BauerLawForlife",
        "Capousemel",
        "Chellonti",
        "Chersino",
        "Collenesu",
        "Compupper",
        "DancerZapMr",
        "DelightShun",
        "Diaworff",
        "GossipKuroGato",
        "GreeChosen",
        "Growerig",
        "Impaktro",
        "Intelagon",
        "Isonince",
        "KavenWetWet",
        "Kilojai",
        "Musenfor",
        "Nycoreska",
        "Orynetie",
        "Praxaly",
        "PrideFeatured",
        "Pupiler",
        "Ribbanker",
        "RipPhreek",
        "RobChan",
        "Roupland"
    ]
    
}
